Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?
7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
число строк которого больше 1 и на 1 меньше, чем число строк двумерного 
массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.
8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?
9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.
10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы.
С помощью функции numpy.where, используя матрицу D_inv в качестве маски,
а матрицы B и C - в качестве источников данных,
получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1,
должны быть равны соответствующему элементу матрицы B,
а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0,
должны быть равны соответствующему элементу матрицы C.

Задание 2
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

Задание 3
Вычислите массив a_centered, отняв от значений массива а 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

Задание 4
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

* Задание 5
Число, которое мы получили в конце задания 4, является 
ковариацией двух признаков, содержащихся в массиве а.
В задании 4 мы делили сумму произведений центрированных 
признаков на N-1, а не на N, поэтому полученная нами величина 
является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Ссылка
В этом задании проверьте получившееся число, вычислив
ковариацию еще одним способом - с помощью функции np.cov.
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [49]:
# Задание 1 Импортируйте библиотеку Numpy и дайте ей псевдоним np.
# 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

import numpy as np

a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [42]:
# 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

a_1 = np.reshape(a, (2, 6))
print(np.shape(a_1))
a_2 = np.reshape(a, (3, 4))
print(np.shape(a_2))
a_3 = np.reshape(a, (6, 2))
print(np.shape(a_3))
a_4 = np.reshape(a, (4, 3))
print(np.shape(a_4))
a_5 = np.array([a[2:4],a[5:7]])
print(np.shape(a_5))

(2, 6)
(3, 4)
(6, 2)
(4, 3)
(2, 2)


In [55]:
# 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape 
# число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

a_1_1 = np.reshape(a, (-1, 6))
print(a_1_1)
a_1_2 = np.reshape(a, (-1, 4))
print(a_1_2)
a_1_3 = np.reshape(a, (6, -1))
print(a_1_3)
a_1_4 = np.reshape(a, (4, -1))
print(a_1_4)
a_1_5 = np.reshape(a, (3, -1))
print(a_1_5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

#  Ответ - Да

In [80]:
# 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, 
# равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, 
# как и исходный массив.

b = np.random.randn(3, 4)
print(np.size(b))
b_flat = b.flatten()
print(np.size(b_flat))

12
12


In [95]:
# 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. Создать массив b, 
# состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
# В чем разница между массивами a и b?

a = np.arange(20, 0, -2)
print(a)
b = np.arange(20, 1, -2)
print(b)

# Вроде нет разницы :(

[20 18 16 14 12 10  8  6  4  2]
[20 18 16 14 12 10  8  6  4  2]


In [103]:
# 7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
# чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

a = np.zeros((2, 2))
print(a)
b = np.ones((3, 2))
print(b)
v = np.vstack((a, b))
print(v)
print(np.size(v))


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


In [115]:
# 8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, 
# чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем 
# транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
# Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

a = np.arange(0, 12)
print(a)
A = np.reshape(a, (4, 3))
print(A)
A_t = A.T
print(A_t)
B = np.dot(A, A_t)
print(B)
print(np.linalg.det(B))

# Вычислить обратную для матрицы B матрицу нельзя, так как детерминант матрицы B равен 0


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
0.0


In [143]:
# 9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. Создайте одномерный массив c, 
# составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. Поменяйте его форму так, 
# чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, 
# умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

np.random.seed(42)
c = np.random.randint(0,16, 16)
print(c)
C = np.reshape(c, (4,4))
print(C)
D = B + C * 10
print(D)
print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))
D_inv = np.linalg.inv(D)
print(D_inv)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]
-28511999.999999944
4
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


In [149]:
# 10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv 
# остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
# а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых 
# соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
# для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
print(D_inv)

E = np.where(D_inv, B, C)
print(E)


[[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]
[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]


In [154]:
# Задание 2 Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
# Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, 
# что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, 
# используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
print(a)
mean_a = a.mean(axis = 0)
print(mean_a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
[2.  8.4]


In [156]:
# Задание 3 Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, 
# содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [166]:
# Задание 4 Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. 
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.

a_centered_sp = a_centered[:,0] @ a_centered[:,1]
print(a_centered_sp)

z = a_centered_sp / 4
print(z)


8.0
2.0


In [169]:
# Задание 5 Число, которое мы получили в конце задания 4, является ковариацией двух признаков, содержащихся в массиве а. 
# В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является 
# несмещенной оценкой ковариации. Подробнее узнать о ковариации можно здесь: Ссылка В этом задании проверьте получившееся число, 
# вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать 
# транспонированный массив a. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет 
#равно элементу в строке с индексом 0 и столбце с индексом 1.

a_t = a.T
print(a_t)
covmatrix = np.cov(a_t)
z == covmatrix[0, 1]

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


True